
const products = [
  {
    name: "sony 24mm GM",
    brand: "Sony",
    category: "lens",
    price: 1000,
    stock: 1,
    description: "",
    imageUrl: "https://gadgetrentalindia.com/wp-content/uploads/2024/03/Sony-24mm-F1.4-GM-Full-Frame-Lens-on-rent-i",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Nikon 35mm Prime Lens",
    brand: "Nikon",
    category: "lens",
    price: 149,
    stock: 1,
    description: "35mm prime lens",
    imageUrl: "https://media.tatacroma.com/Croma%20Assets/Imaging/Camera%20Accessories/Images/170790_0_da2ovx.png",
    isAvailable: true,
    type: "lens"
  },
  {
    name: "Canon 700D",
    brand: "canon",
    category: "cameras",
    price: 699,
    stock: 1,
    description: "700d with lens",
    imageUrl: "https://bragpacker.com/wp-content/uploads/2017/03/Canon-700d-600x360.jpg",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "sony 16-35 GM",
    brand: "sony-lens",
    category: "lenses",
    price: 1100,
    stock: 1,
    description: "sony 16-35 GM",
    imageUrl: "https://media-assets.hyperinvento.com/companies/a3c7bcff-3901-47a9-a4e5-b1d2b32d7abb/products/assets",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Canon R10",
    brand: "canon",
    category: "cameras",
    price: 1299,
    stock: 1,
    description: "R10 Kit with 18-150mm lens",
    imageUrl: "https://in.canon/media/image/2022/05/23/2082b02be46045ad950d44b82c402a14_EOS+R10+w+RF-S18-150mm+f3.5",
    isAvailable: true,
    type: "Mirrorless"
  },
  {
    name: "Tripod Heavy",
    brand: "vanguard",
    category: "tripod",
    price: 400,
    stock: 1,
    description: "Tripod heavy",
    imageUrl: "https://www.digitek.net.in/cdn/shop/files/digitek-dptr-7060vd-platinum-heavy-duty-video-tripod-maxim",
    isAvailable: true,
    type: "Tripod"
  },
  {
    name: "Sony A7M3 with 28-70mm Lens",
    brand: "sony",
    category: "cameras",
    price: 1499,
    stock: 1,
    description: "A7m3 with 28-70mm lens",
    imageUrl: "https://5.imimg.com/data5/ECOM/Default/2024/1/379936059/UQ/FP/SP/4292726/28-336eb04b-780c-434d-8ee1-",
    isAvailable: true,
    type: "Mirrorless"
  },
  {
    name: "Canon 55-250mm Zoom Lens",
    brand: "Canon",
    category: "Lens",
    price: 149,
    stock: 1,
    description: "55-250mm zoom lens",
    imageUrl: "https://www.canon.ca/dam/products/BUSINESS-UNIT/ITCG/Lenses/EF-Lenses/EF-S-55-250mm-f4-5.6-IS-STM/Ca",
    isAvailable: true,
    type: "Zoom"
  },
  {
    name: "Photographer ",
    brand: "Photographer",
    category: "manpower",
    price: 1500,
    stock: 10,
    description: "Event photographer per session",
    imageUrl: "https://static.vecteezy.com/system/resources/previews/044/277/442/non_2x/male-photographer-on-isolat",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "Canon 760D",
    brand: "canon",
    category: "cameras",
    price: 1099,
    stock: 1,
    description: "760D with lens",
    imageUrl: "https://www.mega.pk/items_images/Canon+EOS+760D+18-135mm+Price+in+Pakistan%2C+Specifications%2C+Feat",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "Wireless Mic",
    brand: "digitek",
    category: "mic",
    price: 250,
    stock: 1,
    description: "Wireless mic",
    imageUrl: "https://img.clevup.in/369901/DigitekDWM-1114ChannelWirelessMicrophoneSystem360UltraVoiceCapture24GHz",
    isAvailable: true,
    type: "Microphone"
  },
  {
    name: "DJI SC",
    brand: "DJI",
    category: "gimbal",
    price: 749,
    stock: 1,
    description: "dji sc",
    imageUrl: "https://gaffarbhaiandsons.com/wp-content/uploads/2022/05/DJI-SC-1.png",
    isAvailable: true,
    type: "dji"
  },
  {
    name: "sony 50mm Prime Lens",
    brand: "sony",
    category: "lens",
    price: 299,
    stock: 1,
    description: "50mm Prime lens",
    imageUrl: "https://online.videopro.com.au/content/d/8/8/4/d884a2f4120c13e9031416e4b4bdf41d0ebc41c0_SEL50F18F.jp",
    isAvailable: true,
    type: "lens "
  },
  {
    name: "Nikon D750",
    brand: "nikon",
    category: "cameras",
    price: 1300,
    stock: 1,
    description: "D750 with lens",
    imageUrl: "https://rukminim2.flixcart.com/image/704/844/jyxaw7k0/dslr-camera/6/h/s/d750-d750-nikon-original-ima",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "nikon 750d",
    brand: "Nikon",
    category: "cameras",
    price: 1300,
    stock: 1,
    description: "nikon 750d",
    imageUrl: "https://rukminim2.flixcart.com/image/704/844/jyxaw7k0/dslr-camera/6/h/s/d750-d750-nikon-original-ima",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "Tripod Lightweight",
    brand: "digitek",
    category: "tripod",
    price: 199,
    stock: 1,
    description: "Tripod lightweight",
    imageUrl: "https://www.digitek.net.in/cdn/shop/products/digitek-dtr590-vd-pro-tripod-for-dslr-and-video-cameras",
    isAvailable: true,
    type: "Tripod"
  },
  {
    name: "Nikon D3400",
    brand: "Nikon",
    category: "Camera",
    price: 699,
    stock: 1,
    description: "D3400 with lens",
    imageUrl: "https://images.tokopedia.net/img/cache/500-square/VqbcmM/2020/12/16/b4dca9bd-6898-409e-a847-ce7efb38",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "mono pod",
    brand: "digitek",
    category: "tripod",
    price: 99,
    stock: 1,
    description: "mono pod",
    imageUrl: "https://m.media-amazon.com/images/I/61cENV9P8uL.jpg",
    isAvailable: true,
    type: "Tripod"
  },
  {
    name: "sony 24-70 GM",
    brand: "Sony",
    category: "lens",
    price: 900,
    stock: 1,
    description: "sony 24-70 GM",
    imageUrl: "https://gppro.in/wp-content/uploads/2024/11/SONY-LENS-FE-24-70mm-F2.8-GM-II-GP002614-1.jpg",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Gopro Hero 12 Kit",
    brand: "GoPro",
    category: "Camera",
    price: 800,
    stock: 1,
    description: "Hero 12 kit",
    imageUrl: "https://proaudiovideo.in/wp-content/uploads/GoPro-HERO-12-Accessories-Bundle-Black-Online-Buy-India_",
    isAvailable: true,
    type: "Action"
  },
  {
    name: "Digitek  Continuous Light 150w",
    brand: "godox",
    category: "light",
    price: 599,
    stock: 1,
    description: "Digitek  Continuous Light 150w withstand and softbox",
    imageUrl: "https://www.digitek.net.in/cdn/shop/files/DCL400WBCRPD1of12.png?v=1704184026&width=800",
    isAvailable: true,
    type: "light "
  },
  {
    name: "godox sl200",
    brand: "godox",
    category: "light",
    price: 700,
    stock: 1,
    description: "godox sl200",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3W_slEQrAbqGJxVgefzTrn7Zc1M1kz89e-g&s",
    isAvailable: true,
    type: "light "
  },
  {
    name: "Nikon 35mm Prime Lens",
    brand: "nikon-lens",
    category: "lenses",
    price: 350,
    stock: 1,
    description: "35mm prime lens",
    imageUrl: "https://x.imastudent.com/content/0001710_nikon-af-s-dx-35mm-f18g-lens_500.jpeg",
    isAvailable: true,
    type: "lens"
  },
  {
    name: "LC 500R Light",
    brand: "Godox",
    category: "light",
    price: 450,
    stock: 1,
    description: "LC 500r Light",
    imageUrl: "https://static.wixstatic.com/media/be86a3_bd812d0a52104066b8e137a72b9934d5~mv2.png/v1/fill/w_550,h_5",
    isAvailable: true,
    type: "light "
  },
  {
    name: " godox TT520 II Flash",
    brand: "Godox",
    category: "flash",
    price: 250,
    stock: 1,
    description: "TT520 ii flash",
    imageUrl: "https://m.media-amazon.com/images/I/61sDD1qIhvL.jpg",
    isAvailable: true,
    type: "Flash"
  },
  {
    name: "50mm GM",
    brand: "Sony",
    category: "lens",
    price: 1000,
    stock: 1,
    description: "",
    imageUrl: "https://gppro.in/wp-content/uploads/2024/11/Sony-FE-50mm-1.jpg",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Canon 80D Professional",
    brand: "Canon",
    category: "Camera",
    price: 1199,
    stock: 1,
    description: "80d professional with lens",
    imageUrl: "https://gppro.in/wp-content/uploads/2024/11/80D-1.jpg",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "35mm GM",
    brand: "Sony",
    category: "lens",
    price: 1000,
    stock: 1,
    description: "",
    imageUrl: "https://gadgetrentalindia.com/wp-content/uploads/2023/12/Sony-FE-35mm-f-1.4-GM-Lens-on-rent-in-Chand",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Mobile Gimbal",
    brand: "dji",
    category: "gimbal",
    price: 450,
    stock: 1,
    description: "Mobile gimbal",
    imageUrl: "https://m.media-amazon.com/images/I/61TzT00p9QL._UF1000,1000_QL80_.jpg",
    isAvailable: true,
    type: "Gimbal"
  },
  {
    name: "Canon 50mm Prime Lens",
    brand: "Canon",
    category: "Lens",
    price: 149,
    stock: 1,
    description: "50mm Prime lens",
    imageUrl: "https://5.imimg.com/data5/QZ/AR/VY/SELLER-7840607/oipll8v41ol-500x500.jpg",
    isAvailable: true,
    type: "lens"
  },
  {
    name: "Drone Session Shoot",
    brand: "dji",
    category: "Drone",
    price: 3899,
    stock: 1,
    description: "Drone session shoot",
    imageUrl: "https://www.freeiconspng.com/uploads/drone-with-camera-white-png-image-3.png",
    isAvailable: true,
    type: "Drone Service"
  },
  {
    name: "sony 70-200 GM",
    brand: "Sony",
    category: "lens",
    price: 1000,
    stock: 1,
    description: "sony70-200 GM",
    imageUrl: "https://fotocentreindia.com/wp-content/uploads/Sony-FE-70-200mm-f2.8-GM-II-OSS-Lens-Online-Buy-Mumba",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Canon 1300D",
    brand: "canon",
    category: "cameras",
    price: 599,
    stock: 1,
    description: "1300d with lens",
    imageUrl: "https://i5.walmartimages.com/seo/Canon-EOS-1300D-18-Megapixel-Digital-SLR-Camera-with-Lens-0-71-2-17",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "Nikon D5300",
    brand: "nikon",
    category: "cameras",
    price: 749,
    stock: 1,
    description: "D5300 with lens",
    imageUrl: "https://m.media-amazon.com/images/I/51SRpFIddzL.jpg",
    isAvailable: true,
    type: "DSLR"
  },
  {
    name: "Nikon 70-300mm Zoom Lens",
    brand: "nikon-lens",
    category: "lenses",
    price: 350,
    stock: 1,
    description: "70-300mm zoom lens",
    imageUrl: "https://m.media-amazon.com/images/I/611y1yaU8dL.jpg",
    isAvailable: true,
    type: "Zoom"
  },
  {
    name: "Sony A7M3 Body",
    brand: "sony",
    category: "cameras",
    price: 1199,
    stock: 1,
    description: "A7m3 body",
    imageUrl: "https://x.imastudent.com/content/0003463_sony-alpha-a7-iii-mirrorless-camera-body-only-ilce-7m3_500.",
    isAvailable: true,
    type: "Mirrorless"
  },
  {
    name: "Insta 360 X3 Kit",
    brand: "insta360",
    category: "cameras",
    price: 1000,
    stock: 1,
    description: "Insta 360 x3 kit",
    imageUrl: "https://m.media-amazon.com/images/I/51uLWpiKZjL.jpg",
    isAvailable: true,
    type: "Action"
  },
  {
    name: "sk400v",
    brand: "godox",
    category: "light",
    price: 799,
    stock: 1,
    description: "sk400v  light with stand ",
    imageUrl: "https://x.imastudent.com/content/0046575_godox-sk400ii-v-studio-flash-monolight-2-light-kit_500.jpeg",
    isAvailable: true,
    type: "light "
  },
  {
    name: "RS 3 Gimbal",
    brand: "DJI",
    category: "gimbal",
    price: 1400,
    stock: 1,
    description: "RS 3 Gimbal",
    imageUrl: "https://www.xboom.in/wp-content/uploads/2024/05/6-3.png",
    isAvailable: true,
    type: "dji"
  },
  {
    name: "Tripod High Quality",
    brand: "vanguard",
    category: "Tripod",
    price: 299,
    stock: 1,
    description: "Tripod high quality",
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLV-v3jANeSdMkGG7ONHZw49XOiUSgkDxI-A&s",
    isAvailable: true,
    type: "Tripod"
  },
  {
    name: "Lilliput Monitor",
    brand: "Lilliput",
    category: "accessories",
    price: 500,
    stock: 1,
    description: "Lilliput Monitor",
    imageUrl: "https://cdn11.bigcommerce.com/s-jw7ypwsfet/images/stencil/1280x1280/products/748/1992/1__23527.16047",
    isAvailable: true,
    type: "liliput"
  },
  {
    name: "85mm GM",
    brand: "Sony",
    category: "lens",
    price: 1000,
    stock: 1,
    description: "",
    imageUrl: "https://shopatsc.com/cdn/shop/products/VX9139_B_New-Mid.jpg?v=1624982698",
    isAvailable: true,
    type: "G-Master"
  },
  {
    name: "Canon M50",
    brand: "canon",
    category: "cameras",
    price: 899,
    stock: 1,
    description: "M50 with lens",
    imageUrl: "https://cdn.media.amplience.net/i/canon/eos-m50-fsl_800x500_d13b2840a8db43368af689aea7e1c913?$prod-g",
    isAvailable: true,
    type: "Mirrorless"
  },
  {
    name: "Canon 50mm Prime Lens",
    brand: "Canon",
    category: "lens",
    price: 149,
    stock: 1,
    description: "50mm Prime lens",
    imageUrl: "https://5.imimg.com/data5/QZ/AR/VY/SELLER-7840607/oipll8v41ol-500x500.jpg",
    isAvailable: true,
    type: "lens "
  },
  {
    name: "godox  V860 Flash",
    brand: "godox",
    category: "flash",
    price: 500,
    stock: 1,
    description: "V860 flash",
    imageUrl: "https://m.media-amazon.com/images/I/71900SVShPL._AC_SL1500_.jpg",
    isAvailable: true,
    type: "Flash"
  },
  {
    name: "Canon 40mm Prime Lens",
    brand: "Canon",
    category: "Lens",
    price: 149,
    stock: 1,
    description: "40mm Prime lens",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Canon_EF_40mm_f2.8_STM_9409.jpg",
    isAvailable: true,
    type: "Prime"
  },
  {
    name: "Godox Sk 400",
    brand: "godox",
    category: "light",
    price: 800,
    stock: 1,
    description: "",
    imageUrl: "https://m.media-amazon.com/images/I/81kHaLx49vL.jpg",
    isAvailable: true,
    type: "light "
  }
];

export default products;
